params:
  app_name : "mlops-sagemaker"
  execution_role_arn : 'arn:aws:iam::259768221514:role/mlops-sagemaker-role-123'
  image_ecr_url : "259768221514.dkr.ecr.ap-south-1.amazonaws.com/mlflow-pyfunc:1.24.0"
  region : "ap-south-1"
  s3_bucket_name : "mlops-demo-123"
  experiment_id : "0"
  run_id : "39e49fc195254937b3ff0372505cbd6e"
  model_name : "model"